Revert "usb: host/sl811-hcd: fix sparse warning"
This reverts commit 27bbf2f7dee80fa9a93ee44990fc68871244d3df.

Commit 27bbf2f7dee8 results in the following error when compiling
x86_64:allyesconfig.

sl811_cs.c:(.text+0x1d3cb72): undefined reference to `sl811h_driver'

Fixes: 27bbf2f7dee8 ("usb: host/sl811-hcd: fix sparse warning")
Cc: Lad, Prabhakar <prabhakar.csengg@gmail.com>
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>