mptcp: fix compilation error without MPTCP
Fixing these errors:

  net/core/sock.c: In function 'sock_setsockopt':
  net/core/sock.c:1072:29: error: implicit declaration of function 'is_meta_sk'; did you mean 'inet6_sk'? [-Werror=implicit-function-declaration]
   1072 |                         if (is_meta_sk(sk)) {
        |                             ^~~~~~~~~~
        |                             inet6_sk
  net/core/sock.c:1075:33: error: implicit declaration of function 'mptcp_for_each_sub' [-Werror=implicit-function-declaration]
   1075 |                                 mptcp_for_each_sub(tcp_sk(sk)->mpcb, mptcp) {
        |                                 ^~~~~~~~~~~~~~~~~~
  net/core/sock.c:1075:76: error: expected ';' before '{' token
   1075 |                                 mptcp_for_each_sub(tcp_sk(sk)->mpcb, mptcp) {
        |                                                                            ^~
        |                                                                            ;
  cc1: some warnings being treated as errors
  make[3]: *** [scripts/Makefile.build:262: net/core/sock.o] Error 1

No need to restrict the include of mptcp.h (and inet_common.h), it
doesn't conflict with anything. If CONFIG_MPTCP is not set, structure
and stubs will be available to be able to compile code while still doing
nothing more as expected.

Fixes: 47ffff28d3bf ("mptcp: Support for some more socket-options")
Reviewed-by: Christoph Paasch <cpaasch@apple.com>
Signed-off-by: Matthieu Baerts <matthieu.baerts@tessares.net>