scsi: scsi_transport_sas: select BLK_DEV_BSGLIB
Without CONFIG_BLK_DEV_BSGLIB, we get a link error here:

drivers/scsi/scsi_transport_sas.o: In function `sas_bsg_initialize':
scsi_transport_sas.c:(.text+0xcc0): undefined reference to `bsg_setup_queue'
scsi_transport_sas.c:(.text+0xd10): undefined reference to `bsg_setup_queue'
drivers/scsi/scsi_transport_sas.o: In function `sas_smp_dispatch':
scsi_transport_sas.c:(.text+0xe8c): undefined reference to `bsg_job_done'

This modifies the Kconfig 'select' statement accordingly, and matching
what we do for the other two scsi_transport implementations that use
bsglib.

Fixes: 4ececddd5257 ("scsi: scsi_transport_sas: switch to bsg-lib for SMP passthrough")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Reviewed-by: Christoph Hellwig <hch@lst.de>
Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>