Revert "net: dccp: initialize (addr,port) listening hashtable"
This reverts commit c01abbf0bcb2f58a960fcdc0984916995122d5b8.

Cause build failures when DCCP is modular.

ERROR: "inet_hashinfo2_init" [net/dccp/dccp.ko] undefined!

Signed-off-by: David S. Miller <davem@davemloft.net>