tty/amiserial: Add missing argument for tty_unlock()
commit 53a84b6daa653e23c0b79aa8aaeb75f37c4f994a ("tty_lock: Localise the lock")
missed that 7a29938e8f5532e44c6a564219888d65f158f3da ("drivers/tty/amiserial.c:
add missing tty_unlock") just added a new caller of tty_unlock():

drivers/tty/amiserial.c: In function ‘set_serial_info’:
drivers/tty/amiserial.c:1077: error: too few arguments to function ‘tty_unlock’

Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
Cc: Alan Cox <alan@linux.intel.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>