UPSTREAM: Bluetooth: L2CAP: Fix l2cap_global_chan_by_psm regression
The patch dc1fc2062b1d: "Bluetooth: L2CAP: Fix use-after-free caused
by l2cap_chan_put" from Jul 21, 2022, leads to the following Smatch
static checker warning:

        net/bluetooth/l2cap_core.c:1977 l2cap_global_chan_by_psm()
        error: we previously assumed 'c' could be null (see line 1996)

Bug: 254441685
Fixes: dc1fc2062b1d ("Bluetooth: L2CAP: Fix use-after-free caused by l2cap_chan_put")
Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
Signed-off-by: Luiz Augusto von Dentz <luiz.von.dentz@intel.com>
(cherry picked from commit 1ec025443101b99d61ae1b55486948db165f7381)
Signed-off-by: Lee Jones <joneslee@google.com>
Change-Id: I20b471b7348f5907427918792e77fa7543da51a4