types: Remove CONFIG_64BIT Restriction
Although CONFIG_64BIT is enabled in our defconfig, it looks like this definition
did not extend to files outside the arch/arm64 as evidenced by this compile
error:

../arch/arm64/include/asm/atomic_ll_sc.h:221:1: error: unknown type name 'atomic64_t'; did you mean 'atomic_t'?
  221 | ATOMIC64_OPS(add, add, I)
      | ^
../arch/arm64/include/asm/atomic_ll_sc.h:217:2: note: expanded from macro 'ATOMIC64_OPS'
  217 |         ATOMIC64_FETCH_OP (_relaxed,,  ,  ,         , __VA_ARGS__)      \
      |         ^
../arch/arm64/include/asm/atomic_ll_sc.h:190:42: note: expanded from macro 'ATOMIC64_FETCH_OP'
  190 | __ll_sc_atomic64_fetch_##op##name(s64 i, atomic64_t *v)         \
      |                                          ^
../include/linux/types.h:180:3: note: 'atomic_t' declared here
  180 | } atomic_t;
      |   ^

atomic64_t is defined in include/linux/types.h, and we are compiling for 64 bit,
so we can just remove this restriction.