Revert "mmc: tmio-mmc: Remove .set_pwr() callback from platform data"
This reverts commit 3d55b06414c28ed9e254d97de6bfc493e23d24b2, which
causes a build failure:

drivers/mfd/asic3.c:724:2: error: unknown field 'set_pwr' specified in initializer