ANDROID: Remove ABI Padding From inet_connection_sock
The purpose of commit b32c2be88715593ecf8c3d9ae117735bb0982059 ("ANDROID: GKI: api preservation of struct inet_connection_sock")
is to preserve the kernel ABI for GKI devices. This, however, has a side effect
of producing a bit conversion warning in tcp_timer.h:
(With -Werror on)

../net/ipv4/tcp_timer.c:202:27: error: implicit truncation from 'int' to a one-bit wide bit-field changes value from 1 to -1 [-Werror,-Wsingle-bit-bitfield-constant-conversion]
  202 |                 icsk->icsk_mtup.enabled = 1;
      |                                         ^ ~
1 error generated.

As the xml was updated in the commit and we do not care about GKI here, we can
just revert the ABI changes without making changes to the main xml file.