drivers/mcb: do not set default Kconfig variable to modular
Coverage builds found this build fail in ARM ebsa110_defconfig:

drivers/mcb/mcb-parse.c: In function 'chameleon_parse_cells':
drivers/mcb/mcb-parse.c:105:2: error: implicit declaration of function 'memcpy_fromio' [-Werror=implicit-function-declaration]
cc1: some warnings being treated as errors
make[2]: *** [drivers/mcb/mcb-parse.o] Error 1

A simple bisect will output this:

23a77ed80244e95559d9ba01b785db045fbe2754 is the first bad commit
commit 23a77ed80244e95559d9ba01b785db045fbe2754
Author: Johannes Thumshirn <johannes.thumshirn@men.de>
Date:   Wed Feb 26 17:29:05 2014 +0100

    drivers: Introduce MEN Chameleon Bus

The above commit used "default m" which is wrong.  New drivers
should never be globally enabled with "default y/m".  Whether
this driver makes sense to build on ARM is an independent issue.

Here we delete the "default m" line, which is the equivalent of
"default n".

Cc: Johannes Thumshirn <johannes.thumshirn@men.de>
Cc: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>