thermal: ti-soc-thermal: add missing clk_put()
This patch fixes the following Coccinelle error:

./drivers/thermal/ti-soc-thermal/ti-bandgap.c:1441:1-7: \
	ERROR: missing clk_put; clk_get on line 1290 \
	and execution via conditional on line 1298

Signed-off-by: Luis Henriques <henrix@camandro.org>
Signed-off-by: Eduardo Valentin <edubezval@gmail.com>