codafs: fix build break when CONFIG_PROC_SYSCTL=n
Commit 68c2ff57ee3c ("codafs: fix compile warning when CONFIG_SYSCTL=n")
introduces build breakage, when CONFIG_PROC_SYSCTL=n and
CONFIG_CODA_FS=y:

  fs/built-in.o: In function `init_coda':
  psdev.c:(.init.text+0xc02): undefined reference to `coda_sysctl_init'
  psdev.c:(.init.text+0xc7c): undefined reference to `coda_sysctl_clean'
  fs/built-in.o: In function `exit_coda':
  psdev.c:(.exit.text+0xa9): undefined reference to `coda_sysctl_clean'
  make: *** [.tmp_vmlinux1] Error 1

Signed-off-by: Rakib Mullick <rakib.mullick@gmail.com>
Reported-by: Ingo Molnar <mingo@elte.hu>
Acked-by: Randy Dunlap <randy.dunlap@oracle.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>