RDMA/hns: Fix build error again
commit 689677bc19bbce504040131969f1f00fde71f4af upstream.

This is not the first attempt to fix building random configurations,
unfortunately the attempt in commit f6cf53cbcdff ("RDMA/hns: Fix build
error") caused a new problem when CONFIG_INFINIBAND_HNS_HIP06=m and
CONFIG_INFINIBAND_HNS_HIP08=y:

drivers/infiniband/hw/hns/hns_roce_main.o:(.rodata+0xe60): undefined reference to `__this_module'

Revert commits f6cf53cbcdff ("RDMA/hns: Fix build error") and
c7ca35f18f19 ("RDMA/hns: remove obsolete Kconfig comment") to get back to
the previous state, then fix the issues described there differently, by
adding more specific dependencies: INFINIBAND_HNS can now only be built-in
if at least one of HNS or HNS3 are built-in, and the individual back-ends
are only available if that code is reachable from the main driver.

Fixes: f6cf53cbcdff ("RDMA/hns: Fix build error")
Fixes: c7ca35f18f19 ("RDMA/hns: remove obsolete Kconfig comment")
Fixes: 2f2fe7397a48 ("RDMA/hns: Initialize the PCI device for hip08 RoCE")
Fixes: 74ed12a02f6a ("RDMA/hns: Split hw v1 driver from hns roce driver")
Link: https://lore.kernel.org/r/20191007211826.3361202-1-arnd@arndb.de
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Jason Gunthorpe <jgg@mellanox.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>